#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SignalBLE.Resource", IsApplication=true)]

namespace SignalBLE
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Clipcoin.Phone.Resource.Drawable.enter = global::SignalBLE.Resource.Drawable.enter;
			global::Clipcoin.Phone.Resource.Drawable.exit = global::SignalBLE.Resource.Drawable.exit;
			global::Clipcoin.Phone.Resource.Drawable.main_icon = global::SignalBLE.Resource.Drawable.main_icon;
			global::Clipcoin.Phone.Resource.String.ConfirmEnter = global::SignalBLE.Resource.String.ConfirmEnter;
			global::Clipcoin.Phone.Resource.String.ConfirmExit = global::SignalBLE.Resource.String.ConfirmExit;
			global::Clipcoin.Phone.Resource.String.ConfirmationType = global::SignalBLE.Resource.String.ConfirmationType;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int enter = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int exit = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int main_icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ConfirmEnter = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ConfirmExit = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int ConfirmationType = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
