#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Clipcoin.Application.Resource", IsApplication=true)]

namespace Clipcoin.Application
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Clipcoin.Phone.Resource.Drawable.enter = global::Clipcoin.Application.Resource.Drawable.enter;
			global::Clipcoin.Phone.Resource.Drawable.exit = global::Clipcoin.Application.Resource.Drawable.exit;
			global::Clipcoin.Phone.Resource.Drawable.main_icon = global::Clipcoin.Application.Resource.Drawable.main_icon;
			global::Clipcoin.Phone.Resource.Drawable.sun = global::Clipcoin.Application.Resource.Drawable.sun;
			global::Clipcoin.Phone.Resource.String.ConfirmEnter = global::Clipcoin.Application.Resource.String.ConfirmEnter;
			global::Clipcoin.Phone.Resource.String.ConfirmExit = global::Clipcoin.Application.Resource.String.ConfirmExit;
			global::Clipcoin.Phone.Resource.String.ConfirmationType = global::Clipcoin.Application.Resource.String.ConfirmationType;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060001
			public const int actualSignalCount_Values = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int entries = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_normal = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int coin = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int enter = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int exit = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int main_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sun = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080010
			public const int button_IENTER = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int button_IExit = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int button_login = 2131230725;
			
			// aapt resource value: 0x7f080013
			public const int button_try_again = 2131230739;
			
			// aapt resource value: 0x7f080004
			public const int checkBox_showPassword = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int editText_login = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int editText_password = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int linearLayout1 = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int linearLayout2 = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int linearLayout3 = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int textView1 = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int textView2 = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int textView_BeaconScannerStatus = 2131230734;
			
			// aapt resource value: 0x7f080012
			public const int textView_Log = 2131230738;
			
			// aapt resource value: 0x7f08000b
			public const int textView_SignalsCount = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int textView_TrackerScannerValue = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int textView_login = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int textView_password = 2131230722;
			
			// aapt resource value: 0x7f08000f
			public const int textView_status_position = 2131230735;
			
			// aapt resource value: 0x7f080007
			public const int textView_ts = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Loop = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ConfirmEnter = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ConfirmExit = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int ConfirmationType = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int actualSignalCount_defaultValue = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int actualSignalsCount_key = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int beacon_scan_interval_key = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int first_beacon_address_default_value = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int first_beacon_address_key = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int rssi_treshold_default_value = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int rssi_treshold_key = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int second_beacon_address_default_value = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int second_beacon_address_key = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int tel_send_address_default_value = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTextStyle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int pref = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
