#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Clipcoin.Application.Resource", IsApplication=true)]

namespace Clipcoin.Application
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Clipcoin.Phone.Resource.Drawable.enter = global::Clipcoin.Application.Resource.Drawable.enter;
			global::Clipcoin.Phone.Resource.Drawable.exit = global::Clipcoin.Application.Resource.Drawable.exit;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int entries = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int coin = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int enter = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int exit = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int button_login = 2131165189;
			
			// aapt resource value: 0x7f070011
			public const int button_try_again = 2131165201;
			
			// aapt resource value: 0x7f070004
			public const int checkBox_showPassword = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int editText_login = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int editText_password = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout1 = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout2 = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout3 = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int textView1 = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int textView2 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int textView_BeaconScannerStatus = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int textView_Log = 2131165200;
			
			// aapt resource value: 0x7f07000b
			public const int textView_SignalsCount = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int textView_TrackerScannerValue = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int textView_login = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int textView_password = 2131165186;
			
			// aapt resource value: 0x7f07000f
			public const int textView_status_position = 2131165199;
			
			// aapt resource value: 0x7f070007
			public const int textView_ts = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Loop = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int beacon_scan_interval_key = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int first_beacon_address_default_value = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int first_beacon_address_key = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int rssi_treshold_default_value = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int rssi_treshold_key = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int second_beacon_address_default_value = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int second_beacon_address_key = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int tel_send_address_default_value = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int pref = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
